spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:33060/sfg_prod?autoReconnect=true&useSSL=false
    username: sfg_prod_user
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false